/*
389. Find the Difference

https://leetcode.com/problems/find-the-difference/description/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
/*
Idea - Add the ascii values of chaacters of s into a variable and ascii sum of the characters of t into another variable.
The difference of these two variables gives us the ascii value of the extra character.
*/
class Solution {
    public char findTheDifference(String s, String t) {
        int scount=0;
        int tcount=0;
        for(int i=0;i<s.length();i++)
        {
            scount+=(int)s.charAt(i);
        }
        for(int i=0;i<t.length();i++)
        {
            tcount+=(int)t.charAt(i);
        }
        return (char)(tcount-scount);
    }
}
/*
Time Complexity - O(n+m) where n=length of s, m=length of t
Space Complexity - O(1)
*/
