/*
389. Find the Difference

https://leetcode.com/problems/find-the-difference/description/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
/*
Idea - Use xor operation. We know that 1^1=0, 0^0=0 i.e, x^x^y=0^y=y
Thus we use the above property and xor all the characters in both the strings. Finally, the extra character is left out which is the required result.
*/
class Solution {
    public char findTheDifference(String s, String t) {
        int xor=0;
        for(int i=0;i<s.length();i++)
        {
            xor=xor^s.charAt(i);
        }
        for(int i=0;i<t.length();i++)
        {
            xor=xor^t.charAt(i);
        }
        return (char)xor;
    }
}
/*
Time Compplexity - O(n+m) = O(n+n+1)=O(2n+1)= O(n) where n=length of s, m=length of t=n+1
Space Complexity - O(1)
*/
